apiVersion: v1
kind: Pod
metadata:
  name: ldr
  labels:
    app: ldr
spec:
  containers:
  - name: ldr-container
    image: p2w2/ldr
    volumeMounts:
    - name: tz-config
      mountPath: /etc/localtime
    env:
    - name: SERVER_HOST
      value: "${brokerIP}"
    - name: "DEVICE_NAME"
      value: "${nodeName}"
    securityContext:
      privileged: true
  nodeName: ${nodeName}
  volumes:
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/Europe/Berlin
