apiVersion: v1
kind: Pod
metadata:
  name: ${podname}
  labels:
    app: ${podname}
spec:
  containers:
    - name: ${podname}-container
      image: rajasiman/picamera
      tag: v0.0.1
      securityContext:
        privileged: true
      args:
        - "--resolution"
        - "1920-1080"
        - "--output"
        - "/camera_output/continuous_captures"
        - "--interval"
        - "10"
        - "--iso"
        - "100"
      volumeMounts:
        - name: camera-volume
          mountPath: /camera_output/continuous_captures # same mount path as args above # can use variables in helm charts
  volumes:
    - name: camera-volume
      persistentVolumeClaim:
        claimName: picamera-volume
    - name: dev-vcsm
      hostPath:
        path: /dev/vcsm
    - name: dev-vchiq
      hostPath:
        path: /dev/vchiq

  nodeName: ${nodeName}
