kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: picamera-volume
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: zerops-nfs
