apiVersion: v1
kind: Pod
metadata:
  name: camera
  labels:
    app: camera
spec:
  containers:
  - name: camera-container
    image: p2w2/camera
    securityContext:
      privileged: true
  nodeSelector:
    sensor: camera

