apiVersion: v1
kind: Pod
metadata:
  name: light
  labels:
    app: light
spec:
  containers:
    - name: light-container
      image: p2w2/light
      volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      env:
        - name: SERVER_HOST
          value: "${brokerIP}"
        - name: "DEVICE_NAME"
          value: "${nodeName}"
      securityContext:
        privileged: true
  nodeName: ${nodeName}
  volumes:
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/Europe/Berlin
