apiVersion: v1
kind: Pod
metadata:
  name: temphumdity
  labels:
    app: temphumdity 
spec:
  containers:
  - name: temp-humidity-container
    image: shrihari93/dsproject:dht_sensor
    env:
    - name: SERVER_HOST
      value: "10.43.131.239"
    securityContext:
      privileged: true

  nodeSelector:
    sensor: dht_22
